#!/usr/bin/env bash


set -e
unset PYTHONPATH
unset R_LIBS_SITE


# SET DEFAULT ARGUMENTS
SCRIPTDIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
PIPELINEDIR=$(dirname "${SCRIPTDIR}")
source "${PIPELINEDIR}"/CONFIG
COMBINE_CONTROLS=FALSE


# PARSE COMMAND LINE ARGUMENTS
while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h|--help)
      echo "_____________"
      echo "ProcessCounts"
      echo "‾‾‾‾‾‾‾‾‾‾‾‾‾"
      echo "Process FASTQ read counts with DESeq2 (https://github.com/mikelove/DESeq2) to obtain "
      echo "enrichment values and an analysis summary full of quality-control figures."
      echo ""
      echo "For help using the ProcessCounts pipeline, visit "
      echo "https://fazallabbcm.github.io/FazalLabPipelines/."
      echo ""
      echo "____________________________________________________________________________________________"
      echo "Usage:"
      echo "  ProcessCounts --option <argument>"
      echo ""
      echo "Options:"
      echo "  -h, --help                show this help message"
      echo ""
      echo "  -d, --data-dir DIR        path to directory containing processed data files"
      echo ""
      echo "  -o, --output-dir DIR      path to directory for output tables and figures"
      echo "                            (default is your current directory)"
      echo ""
      echo "  -n, --name NAME           name of project to be added to file names of tables and figures"
      echo "                            (default is ProjectName)"
      echo ""
      echo "  -c, --combine-controls    if control samples for each experimental condition are the same, "
      echo "                            they can be combined for improved analysis and figures"
      echo "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾"
      exit 0
      ;;
    -d|--data-dir)
      DATADIR="${2}"
      shift
      shift
      ;;
    -o|--output-dir)
      OUTPUTDIR="${2}"
      shift
      shift
      ;;
    -n|--name)
      PROJECT_NAME="${2}"
      shift
      shift
      ;;
    -c|--combine-controls)
      COMBINE_CONTROLS=TRUE
      shift
      ;;
    -e|--env-dir)
      ENVDIR="${2}"
      shift
      shift
      ;;
    -t|--temp-dir)
      TEMPDIR="${2}"
      shift
      shift
      ;;
    -*|--*)
      echo "Unknown option: ${1}"
      exit 1
      ;;
    *)
      echo "Unknown argument: ${1}"
      exit 1
      ;;
  esac
done


# HANDLE UNSPECIFIED ARGUMENTS
if [[ -z "${DATADIR}" ]]
then
  echo "  Processed data directory not specified. Please supply path to processed data directory."
  exit 1
fi
if [[ -z "${OUTPUTDIR}" ]]
then
  OUTPUTDIR="${PWD}"
fi
if [[ -z "${PROJECT_NAME}" ]]
then
  PROJECT_NAME=ProjectName
fi


# PREPARE ENVIRONMENT
# Activate environment
export PATH="${ENVDIR}"/bin:"${PATH}"
# Avoid dumping too much temporary data into system tmp directory
export TMPDIR="${TEMPDIR}"
export TEMP="${TEMPDIR}"
export TMP="${TEMPDIR}"


# PRINT SETTINGS FOR USER
echo ""
echo "  Processed data directory:  ${DATADIR}"
echo "  Output directory:          ${OUTPUTDIR}"
echo "  Project name:              ${PROJECT_NAME}"
echo "  Combine controls:          ${COMBINE_CONTROLS}"
#echo "  Environment directory:     ${ENVDIR}"
#echo "  Temporary directory:       ${TEMPDIR}"
echo ""
echo "  Log file will be created in your current directory:  ${PWD}"
echo ""


# START PIPELINE
while true
do
  read -p "Do you wish to start the ProcessCounts pipeline? [y/n] " yn
  case $yn in
    [Yy]*)
      sbatch "${SCRIPTDIR}"/ProcessCounts.sh "${SCRIPTDIR}" "${DATADIR}" "${OUTPUTDIR}" "${PROJECT_NAME}" "${COMBINE_CONTROLS}"
      break
      ;;
    [Nn]*)
      exit 0
      ;;
    *)
      echo "  Please answer yes or no."
      ;;
  esac
done

